### ISSUE TITLE
things to clarify in README

### ISSUE THREAD

**Issue by vrabaud** [aldebaran/libqi#13]
I believe the following could be improved:
- [x]  instructions on how to build (or at least a link to qibuild).
- [ ]  details on which OS / libraries / languages are supported / not supported and with which versions.
- [x]  I don't think the maintainers listed there read their emails anymore.
- [x]  the mailing list is the one for qibuild, is that normal ?
- [ ]  links to who's using it, connected projects (libqicore), bindings

**Comment by alkino** [comment]
Partially fixed with 99d650d1282f6b78eca6 and caa3c6e2b0b1de81088dd
