### ISSUE TITLE
Recompiling C++ NAO SDK for VS2015?

### ISSUE THREAD

**Issue by 1337SEnergy** [aldebaran/libqi#17]
I know that this might be really really bad place to ask this, but I've been trying to figure out how to do this for several hours now and only thing I stumbled upon was this; https://community.ald.softbankrobotics.com/en/forum/visual-studio-2015-and-c-sdk-6663

therefore I came here for help...

I need to recompile the C++ SDK for NAO so that I can use it with Visual Studio 2015 (yes, it really is necessary and no I can't use 2010), however as I do not have that much experience with libraries and I see no CMake list or anything that I could use to recompile it I have no idea what to do now

I have installed qibuild, downloaded libqi and C++ NAO SDK, please for heaven's sake could someone help me recompile this? what do I need? where do I look? I'm kinda desperate here, all I need is to use C++ library with visual studio 2015

**Comment by Klaim** [comment]
I believe it is possible to recompile libqi with VS2015 with minor fixes, but I never tried to do it outside our internal tools at aldebaran.
Anyway, if you have cmake, qibuild and all dependencies (toolchains) ready, just use the CMakeLists.txt at the root of libqi repository for this part.
Maybe I misunderstood your questions so feel free to clarify so that I can help you.

**Comment by RealSEnergy** [comment]
1. what toolchains would I need?
2. I kinda don't even know what libqi is, I just got here from the thread I linked above

I just started with NAO at my university few weeks ago (I've been just playing with choreographe till now) and was assigned to do a project in 1 week as we'll have kids from elementary school coming in and I'm not sure how I can use libqi (I browsed some examples here on github but it doesn't look as something I could use) 

what I need is a way to use the NAO API (the AL modules for speech, movement etc) in visual studio 2015 using C++ (as I'm creating UWP app as a NAO Dashboard and am experienced only with C++)

I tried to do behavior scripts using python and then call them using C++, unfortunately python doesn't work with UWP for some reason (confirmed several times by other people trying to integrate python to UWP as well) so I'm stuck now

**Comment by Klaim** [comment]
To be short, this repository's library, libqi, provide the C++ type marshalling, inter-process transfert and RPC protocol on which all the Naoqi system relies on. I'm not sure what version of Naoqi you have but this repository represent the 2+ versions of Naoqi which is mostly compatible with previous versions as long as you manipulate services through the right remote objects.

If you build an application using libqi, you can get objects representing the remote services you need to communicate with and manipulate the robot. This way of making an application only work outside Choregraphe though.

Now your questions:

> what toolchains would I need?

If you want to develop on the robot, you need the toolchain for it. I'm not sure how non-employees of the company get them (I've been here for 2 years but I have access to internal tools). I will check with my colleagues. Anyway once you have the URL of the toolchain, just use `qitoolchain` tool to install it, then `qibuild add-config` to configure it in a work tree, then 

>
