### ISSUE TITLE
Can we release it for ROS Lunar?

### ISSUE THREAD

**Issue by nlyubova** [aldebaran/libqi#21]

**Comment by vpaleologue-aldebaran** [comment]
What do you mean exactly?
We cannot target a ROS version for a release.

**Comment by nlyubova** [comment]
We can, if it is a ROS package, it seems that it is already exists for Indigo, and Kinetic based on http://wiki.ros.org/naoqi_libqi , if it is the same package

**Comment by vpaleologue-aldebaran** [comment]
It should be pretty easy, but it seems it would happen here: https://github.com/ros-naoqi/libqi-release and here: https://github.com/ros-naoqi/libqicore-release. Let's follow that discussion there.
