### ISSUE TITLE
How can I build code successful in ubuntu16.04 with C++ SDK?

### ISSUE THREAD

**Issue by SkyCloudShang** [aldebaran/libqi#22]
when I use the  naoqi-sdk-2.1.4.13-linux64 in my ubuntu16.04, I cannot build the code successful while in ubuntu14.04 it indeed successed.
      In your team's github resources,I find someone else has the same issues as me(https://github.com/aldebaran/libqi/issues/18). In your team's reply,I get the conclusion that the current naoqi-sdk-2.1.4.13-linux64 only support boost 1.55 while ubuntu16.04 has the 1.58 version. As a result.they cannot linked successful.
      Owing that issue,I get the idea that I can install boost1.55 in my PC,then I installed it .However , I cannot build the example success as well. What can I do next? When would the SDK will support ubuntu16.04 or some vresions above such as ubuntu17.04 or even higher?What is the easist way for me to deal with this problem?

Wish you could give me  some advice. Thanks.

![image](https://user-images.githubusercontent.com/8363142/33202956-5751fd88-d139-11e7-801a-eead04e1e8be.png)

**Comment by vpaleologue-aldebaran** [comment]
Sorry, this is not the place for this, it is not the same issue as #18. Please try https://developer.softbankrobotics.com/us-en/forum or https://stackoverflow.com/questions/tagged/nao-robot?mixed=1 for help.

**Comment by sbarthelemy** [comment]
Hello,
while not regularly tested nor officially supported, I think compiling libqi on ubuntu 16.04 should wotrk fine if you use boost (version 1.55) packaged in this toolchain
https://github.com/aldebaran/toolchains/blob/master/feeds/linux64.xml

**Comment by Klaim** [comment]
@sbarthelemy It's boost 1.59 in this toolchain, but indeed it should work fine.

@SkyCloudShang Victor's and Sebastien's answers are spot-on.
