### ISSUE TITLE
Problem regarding the language compatibilty in Choregraphe project

### ISSUE THREAD

**Issue by soumenms2015** [aldebaran/libqi#24]
My Pepper currently have one Project which supports both language English and German. But Now one new Project which I tried to run in Pepper, Support only English but it doesn't work and gives me the below error.  I tried to add German language by going to porject properties but it still gives same error. 

Any Kind of help will be appreciated.

[ERROR] audio.alspeechrecognition :xTryTriggerSignsAndFeedback:0 Didn't trigger ExpressiveBit BeginSpeechRecognitionEyes: Cannot find service 'ALSignsAndFeedback' in index
 [ERROR] behavior.translator :load:0 Fail to load translation for '/home/nao/.local/share/PackageManager/apps/.lastUploadedChoregrapheBehavior' lang 'de_DE'

Thank you very much for your Kind support

**Comment by victorpaleologue** [comment]
I'm sorry but the project libQi is not about Choregraphe.
Have you tried on StackOverflow?
The tags "nao-robot", "pepper" and "choregraphe" are usually watched, there.

**Comment by soumenms2015** [comment]
I have already posted there but there was no response. You guys don't have any proper platform for addressing any technical issue. This is very unfortunate. The community platform is very pathetic as the page is never loaded properly always. :(
