### ISSUE TITLE
Installation issue with the NAOqi python SDK on Ubuntu

### ISSUE THREAD

**Issue by nyibbang** [aldebaran/libqi#28]
Can anyone help with detailed installation process of NAOqi SDK (python) on Ubuntu. The installation process on the official page is not detailed enough for beginners.

_Originally posted by @OlalekanIsola in https://github.com/aldebaran/libqi/issues/18#issuecomment-566969648_

**Comment by nyibbang** [comment]
@OlalekanIsola Hello, I assume you tried following the instructions from this [page](http://doc.aldebaran.com/2-5/dev/python/install_guide.html).
What was your issue ? Please add information on the steps that you did and on the problem that occurred.
Also note that the NAOqi python SDK is no longer updated and its support will be dropped in a near future. We know distribute the python binding for libqi as a pypi package available [here](https://pypi.org/project/qi), that you can install through pip.

**Comment by OlalekanIsola** [comment]
Hi Vincent,

Yes, I followed the instructions on the page. Jetson Nano runs on Ubuntu
18.04. I need to install the NAOqi SDK for me to be able to use the* import
naoqi*. This is really crucial for my project as its allows me to work with
the NAO

**Comment by nyibbang** [comment]
Understood. Note that this version of the NAOqi python SDK only supports Ubuntu 14.04, and the pip package only supports Ubuntu 16.04.

Please verify that:
- the archive was successfully extracted.
- you set the PYTHONPATH accordingly (`export PYTHONPATH=${PYTHONPATH}:<path-where-you-extracted>/lib/python2.7/site-packages`).
- you use the python2.7 interpreter (`python --version`).

**Comment by OlalekanIsola** [comment]
You have been very helpful. I can verify that I did all the listed items.
Thank you Vincent, you have been really helpful

**Comment by Klaim** [comment]
Did checking these fix your problem? or did you use pip?

**Comment by OlalekanIsola** [comment]
Pip does not have the Naoqi package. Vincent willing to help, but I am
afraid , Naoqi only supports Ubuntu 14.04. Jetson Nano Runs on 18.04.

**Comment by Klaim** [comment]
Vincent and I are part of the team that maintain libqi and libqi-python among other things. He is correct. 

The Python SDK is not supported on recent Ubuntu or any other platforms and you need to use pip to get libqi-python that you can use to develop python applications for Naoqi. Naoqi (the robotic platform, not the sdk) itself is not distributed for desktop anymore for new versions.

The right package in pip is `libqi` so this should work:  `pip install libqi`

Once you've done that you can use `import qi` in your python scripts.

**Comment by Klaim** [comment]
Correction: Last supported version is Ubuntu 16.04, you can find the sdk there: http://doc.aldebaran.com/index.html 

Using either pip or this sdk should work if you are on Ubuntu 16.04.

**Comment by robertanto** [comment]
> Hi Vincent, Yes, I followed the instructions on the page. Jetson Nano runs on Ubuntu 18.04. I need to install the NAOqi SDK for me to be able to use the* import naoqi*. This is really crucial for my project as its allows me to work with the NAO

@OlalekanIsola I have just published a pre-compiled version of the qi SDK that works on Ubuntu 18.
https://github.com/robertanto/libqi-python-nvidia-jetson

**Comment by UdayRockzz** [comment]
Does anyone have Naoqi SDK ? I am following these [steps.](http://wiki.ros.org/nao/Tutorials/Installation) but I am unable to find Naoqi SDK but I have found Python bindings. It will be a great if anyone share Naoqi SDK to me.  Thanks in advance.
