### ISSUE TITLE
How to get angle velocity

### ISSUE THREAD

**Issue by 0aqz0** [aldebaran/libqi#32]
Joint control APIs described in [docs](http://doc.aldebaran.com/2-1/naoqi/motion/control-joint-api.html#ALMotionProxy::changeAngles__AL::ALValueCR.AL::ALValueCR.floatCR) only allow us to get the current joint angles.
How can I access the angle velocities?
Thank you very much if you can provide any suggestions.

**Comment by sbarthelemy** [comment]
Hello,

NAO and Pepper joints don't have speed sensors, and there is no API exposing the speed on recent version of NAOqi (>=2.8.5 and >=2.9).
You can compute it with numeric differentiation.

On older versions of NAOqi, the speed (computed by differentiation) was published on ALMemory keys named like Motion/Velocity/Sensor/HeadPitch.
