### ISSUE TITLE
Unable to find Naoqi SDK

### ISSUE THREAD

**Issue by UdayRockzz** [aldebaran/libqi#34]
Does anyone have Naoqi SDK ? I am following these [steps.](http://wiki.ros.org/nao/Tutorials/Installation) but I am unable to find Naoqi SDK but I have found Python bindings. It will be a great if anyone share Naoqi SDK to me. Thanks in advance.

**Comment by nyibbang** [comment]
Hello @UdayRockzzL. The NAOqi SDK is available on the Softbank Robotics Developer Center (https://developer.softbankrobotics.com) and on the EMEA Support Center (https://www.softbankrobotics.com/emea/en/support).

For instance, you can find the SDK for NAO robots by following this link
https://www.softbankrobotics.com/emea/en/support/nao-6/downloads-softwares/former-versions?os=49&category=76. You may use NAOqi SDK v2.8.x with NAOv6, and NAOqi SDK v2.1.4 with previous versions of NAO.

**Comment by nyibbang** [comment]
The NAOqi SDK is a set of tools and libraries that you can use to develop native (in C/C++) applications or programs for your robot. The PyNAOqi SDK is simply a Python module to develop Python applications for your robot. It does not include any tools or documentation about the APIs that the NAOqi SDK offers.
