### ISSUE TITLE
Max 5 params for a module method

### ISSUE THREAD

**Issue by fieldfoxWim** [aldebaran/libqi#5]
Hi All

I have been struggling to find out why a module method, only supports 5 params. After searching on forums I finaly landed on the libqi source. 
Can somebody confirm that lines 167 and further in libqi/qi/anyfunction.hpp are causing that limitation?
Thanks in advance

```
    class MathModule(ALModule):
        def __init__(self, name):
            ALModule.__init__(self, name)

        def sum(self, a, b, c, d, e):
            """ WORKING """
            print a + " " + b + " " + c + " " + d + " " + e

        def sum1(self, a, b, c, d, e, f):
             """ METHOD UNDEFINED """
             print a + " " + b + " " + c + " " + d + " " + e + " " + f
```

Thanks for your time

Best regards
Wim

**Comment by cgestes** [comment]
libqi support 8 arguments (including self).

The limitation to 6 arguments comes from the old ALModule wrapper.
